---
- name: Install Wazo repo package source
  include_role:
    name: debian-repo-wazo

- name: Create/Configure SSL certs
  include_role:
    name: wazo-certs

- name: Install wazo-confgend-client
  apt:
    name: wazo-confgend-client
    state: present

- name: Install RabbitMQ
  include_role:
    name: wazo-message-bus

- name: Create /var/lib/wazo
  file:
    path: /var/lib/wazo
    state: directory

- name: Disable Wazo services
  file:
    path: /var/lib/wazo/disabled
    state: touch

- name: Create wazo-calld config dir
  file:
    path: /etc/wazo-calld/conf.d
    state: directory

- name: Add wazo-calld config
  template:
    src: templates/wazo-calld.yml.j2
    dest: /etc/wazo-calld/conf.d/50-engine-api.yml
    owner: root
    group: root
    mode: 0644
  when:
    - ari_password is defined
    - ari_username is defined
    - b2bua_host is defined
    - b2bua_port_http is defined

- name: Install wazo-calld
  apt:
    name: wazo-calld
    state: present

- name: Create wazo-amid config dir
  file:
    path: /etc/wazo-amid/conf.d
    state: directory

- name: Add wazo-amid config
  template:
    src: templates/wazo-amid.yml.j2
    dest: /etc/wazo-amid/conf.d/50-engine-api.yml
    owner: root
    group: root
    mode: 0644
  when:
    - ami_password is defined
    - ami_username is defined
    - b2bua_host is defined
    - b2bua_port_ami is defined
    - b2bua_port_http is defined

- name: Install wazo-amid
  apt:
    name: wazo-amid
    state: present

- name: Preconfigure database initialization
  debconf:
    name: xivo-manage-db
    question: xivo-manage-db/db-skip
    vtype: boolean
    value: true

- name: Create wazo-confd config dir
  file:
    path: /etc/wazo-confd/conf.d
    state: directory

- name: Add wazo-confd config
  template:
    src: templates/wazo-confd.yml.j2
    dest: /etc/wazo-confd/conf.d/50-engine-api.yml
    owner: root
    group: root
    mode: 0644
  notify: restart wazo-confd
  when:
    - ari_password is defined
    - ari_username is defined
    - b2bua_host is defined
    - b2bua_port_http is defined
    - b2bua_port_sysconfd is defined
    - engine_api_db_confd_name is defined
    - engine_api_db_confd_password is defined
    - engine_api_db_confd_user is defined
    - engine_api_db_host is defined
    - engine_api_db_port is defined

- name: Create xivo-dao config dir
  file:
    path: /etc/xivo-dao/conf.d
    state: directory

- name: Add xivo-dao config
  template:
    src: templates/xivo-dao.yml.j2
    dest: /etc/xivo-dao/conf.d/50-engine-api.yml
    owner: root
    group: root
    mode: 0644
  notify: restart wazo-confd
  when:
    - engine_api_db_confd_name is defined
    - engine_api_db_confd_password is defined
    - engine_api_db_confd_user is defined
    - engine_api_db_host is defined
    - engine_api_db_port is defined

- name: Install wazo-confd
  apt:
    name: wazo-confd
    state: present

- name: Install wazo-confd-client-python3
  apt:
    name: wazo-confd-client-python3
    state: present

- name: Create wazo-confgend config dir
  file:
    path: /etc/wazo-confgend/conf.d
    state: directory

- name: Add wazo-confgend config
  template:
    src: templates/wazo-confgend.yml.j2
    dest: /etc/wazo-confgend/conf.d/50-engine-api.yml
    owner: root
    group: root
    mode: 0644
  when:
    - engine_api_db_confd_name is defined
    - engine_api_db_confd_user is defined
    - engine_api_db_confd_password is defined
    - engine_api_db_host is defined
    - engine_api_db_port is defined
    - engine_api_port_confgend is defined
    - engine_api_listen_address is defined

- name: Install wazo-confgend
  apt:
    name: wazo-confgend
    state: present

- name: Create wazo-agid config dir
  file:
    path: /etc/wazo-agid/conf.d
    state: directory

- name: Add wazo-agid config
  template:
    src: templates/wazo-agid.yml.j2
    dest: /etc/wazo-agid/conf.d/50-engine-api.yml
    owner: root
    group: root
    mode: 0644
  when:
    - engine_api_db_confd_name is defined
    - engine_api_db_confd_user is defined
    - engine_api_db_confd_password is defined
    - engine_api_db_host is defined
    - engine_api_db_port is defined
    - engine_api_listen_address is defined

- name: Install xivo-config
  apt:
    name: xivo-config
    state: present

- name: Install wazo-agid
  apt:
    name: wazo-agid
    state: present

- name: Install wazo-websocketd
  apt:
    name: wazo-websocketd
    state: present

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Install wazo-nginx
  apt:
    name: wazo-nginx
    state: present
  notify:
    - restart nginx

- name: Install wazo-provd
  apt:
    name: wazo-provd
    state: present

- name: Enable Wazo services
  file:
    path: /var/lib/wazo/disabled
    state: absent

- include_tasks: tracing.yml

