- name: Check version
  ansible.builtin.shell: |
    vers={{ wazo_distribution }};
    echo ${vers##*-} $(cat /usr/share/wazo/WAZO-VERSION);
    test ${vers##*-} = $(cat /usr/share/wazo/WAZO-VERSION)
  when: wazo_debian_repo == "archive"
  changed_when: false

- name: Get token
  ansible.builtin.uri:
    url: "https://{{ engine_api_host }}:{{ engine_api_port }}{{ engine_auth_path }}/token"
    method: POST
    validate_certs: false
    body_format: json
    force_basic_auth: true
    user: "{{ api_client_name }}"
    password: "{{ api_client_password }}"
    body:
      expiration: 3600
    return_content: true
  register: token_data

- name: Debug token data
  ansible.builtin.debug:
    var: token_data

- name: Get users
  ansible.builtin.uri:
    url: "https://{{ engine_api_host }}:{{ engine_api_port }}{{ engine_confd_path }}/users"
    headers:
      X-Auth-Token: "{{ token_data.json.data.token }}"
    method: GET
    validate_certs: false
    return_content: true
  register: users_data

- name: Debug users data
  ansible.builtin.debug:
    var: users_data
