---
- name: Assert Debian Buster
  assert:
    that: ansible_distribution == 'Debian' and ansible_distribution_major_version == '10'

- name: Validate database names
  assert:
    that:
      - engine_api_db_confd_name == engine_api_db_auth_name
  when:
    - engine_api_db_confd_name is defined
    - engine_api_db_auth_name is defined

- name: Assert root password for setup
  assert:
    that:
      - engine_api_root_password is defined
    fail_msg: "The variable engine_api_root_password is required when configuring the wizard."
  when:
    - engine_api_configure_wizard == "true"

- name: Check if /etc/default/locale exists
  stat:
    path: /etc/default/locale
  register: stat_result

- name: Assert UTF-8 locale
  shell: grep 'LANG=.*\.UTF-8"\?$' /etc/default/locale
  when: stat_result.stat.exists == True
