---
# Used to switch to user postgres
- name: Install sudo
  ansible.builtin.apt:
    name: sudo
    state: present

- name: Ensure PostgreSQL Python libraries are installed.
  ansible.builtin.apt:
    name: python3-psycopg2
    state: present


# The role does not handle changing the port while changing users.
# See https://github.com/geerlingguy/ansible-role-postgresql/issues/51
- name: Change PostgreSQL port
  ansible.builtin.include_role:
    name: geerlingguy.postgresql
  vars:
    postgresql_version: 15
    postgresql_data_dir: "/var/lib/postgresql/15/main"
    postgresql_bin_path: "/usr/lib/postgresql/15/bin"
    postgresql_config_path: "/etc/postgresql/15/main"
    postgresql_daemon: "postgresql@15-main"
    postgresql_packages:
      - postgresql-15
      - postgresql-contrib
      - libpq-dev
    postgresql_global_config_options:
      - option: port
        value: "{{ postgresql_port | default(5432) }}"
    postgresql_users: []

- name: Set PostgreSQL superadmin password
  ansible.builtin.include_role:
    name: geerlingguy.postgresql
  vars:
    postgresql_version: 15
    postgresql_data_dir: "/var/lib/postgresql/15/main"
    postgresql_bin_path: "/usr/lib/postgresql/15/bin"
    postgresql_config_path: "/etc/postgresql/15/main"
    postgresql_daemon: "postgresql@15-main"
    postgresql_packages:
      - postgresql-15
      - postgresql-contrib
      - libpq-dev
    postgresql_users:
      - name: postgres
        password: "{{ postgresql_superuser_password }}"
        port: "{{ postgresql_port | default(5432) }}"
  when: postgresql_superuser_password is defined

- name: Set PostgreSQL HBA
  ansible.builtin.set_fact:
    default_hba:
      - {type: local, database: all, user: postgres, auth_method: peer}
      - {type: local, database: all, user: all, auth_method: peer}
      - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5}
      - {type: host, database: all, user: all, address: '::1/128', auth_method: md5}
    external_hba:
      - {type: host, database: all, user: all, address: all, auth_method: md5}

- name: Configure PostgreSQL
  ansible.builtin.include_role:
    name: geerlingguy.postgresql
  vars:
    postgresql_version: 15
    postgresql_data_dir: "/var/lib/postgresql/15/main"
    postgresql_bin_path: "/usr/lib/postgresql/15/bin"
    postgresql_config_path: "/etc/postgresql/15/main"
    postgresql_daemon: "postgresql@15-main"
    postgresql_packages:
      - postgresql-15
      - postgresql-contrib
      - libpq-dev
    postgresql_hba_entries: >
       {{ default_hba + external_hba
          if postgresql_listen_addresses is defined and postgresql_listen_addresses != '127.0.0.1'
          else default_hba }}
    postgresql_global_config_options:
      - option: port
        value: "{{ postgresql_port | default(5432) }}"
      - option: listen_addresses
        value: "{{ postgresql_listen_addresses | default('127.0.0.1') }}"
