---
- hosts: all
  become: yes
  roles:
    - role: preflight_checks

- hosts:
    - all
  become: yes
  roles:
    - role: debian_upgrade_first

- hosts:
    - sbc
  become: yes
  roles:
    - role: c4-sbc
