---
- hosts: all
  become: yes
  roles:
    - role: preflight_checks

- hosts:
    - database
    - router-api
  become: yes
  roles:
    - role: debian_upgrade_first

- import_playbook: postgresql.yml

- hosts: router-api
  become: yes
  roles:
    - role: router