- name: Restart wazo-confd
  ansible.builtin.service:
    name: wazo-confd
    state: restarted

- name: Restart wazo-confgend
  ansible.builtin.service:
    name: wazo-confgend
    state: restarted

- name: Restart wazo-agid
  ansible.builtin.service:
    name: wazo-agid
    state: restarted
