- name: Reload asterisk dialplan
  ansible.builtin.command: asterisk -rx 'dialplan reload'

- name: Reload asterisk manager
  ansible.builtin.command: asterisk -rx 'manager reload'

- name: Reload asterisk
  ansible.builtin.command: asterisk -rx 'core reload'
