---
- name: Upgrade Debian before anything
  apt:
    update_cache: true
    upgrade: dist
  when:
    - debian_upgrade_first
    - debian_upgrade_first_done is undefined
  register: debian_upgrade_first_done
