---
- name: Install the ntp and postfix daemons
  # Some machines have chrony installed
  apt:
    name:
      - ntp
      - postfix
    state: present

- name: Ensure sendmail is absent
  # Debian buster: If sendmail-bin is removed but not purged, dpkg will refuse to do anything
  # See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939885
  apt:
    name: sendmail-bin
    purge: yes
    state: absent

- name: Install Consul
  include_role:
    name: wazo-consul

# need to run after wazo_consul to have wazo_consul_token registered
- name: Set default values
  include_role:
    name: wazo-default

- name: "Install {{ wazo_meta_package }}"
  apt:
    name: "{{ wazo_meta_package }}"
    state: present

- name: Install wazo-setupd
  apt:
    name: wazo-setupd
    state: present

- name: Install nestbox plugin
  apt:
    name:
      - wazo-deployd-client
      - wazo-nestbox-plugin
    state: present
  notify: restart wazo-setupd

- name: Ensure that asterisk has been started with wazo-confgend config
  service:
    name: asterisk
    state: restarted

- name: Change Wazo distribution for later upgrades # noqa 301
  command: wazo-dist --{{ wazo_debian_repo_upgrade }}-repo {{ wazo_distribution_upgrade }}

- name: Finalize engine configuration
  block:
  - name: Setup engine
    uri:
      url: "https://{{ engine_api_host }}:{{ engine_api_port }}{{ engine_setupd_path }}/setup"
      method: POST
      timeout: 300
      validate_certs: no
      body_format: json
      body:
        engine_internal_address: "{{ engine_api_host }}"
        engine_language: "{{ engine_language }}"
        engine_license: true
        engine_password: "{{ engine_api_root_password|string }}"
      status_code: 201

  - name: Create tenant
    command: "wazo-auth-cli tenant create {{ tenant_name }}"

  - name: Create API client
    command: "wazo-auth-cli user create {{ api_client_name }} --tenant {{ tenant_name }} --password {{ api_client_password }} --purpose external_api"

  - name: Create policy
    command: "wazo-auth-cli policy create api-client-policy --tenant {{ tenant_name }} --acl 'confd.#'"

  - name: Enable policy for API client
    command: "wazo-auth-cli user add {{ api_client_name }} --policy api-client-policy"
  when: engine_api_configure_wizard == "true"
