---
- name: Install Wazo repo package source
  ansible.builtin.include_role:
    name: debian-repo-wazo

- name: Create/Configure SSL certs
  ansible.builtin.include_role:
    name: wazo-certs

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Install wazo-nginx
  ansible.builtin.apt:
    name: wazo-nginx
    state: present
  notify:
    - Restart nginx

- name: Install custom certificate for HTTPS
  ansible.builtin.copy:
    src: "{{ engine_api_https_cert }}"
    dest: /usr/share/wazo-certs/server.crt
    owner: root
    group: www-data
    mode: "0640"
  when: engine_api_https_cert is defined
  notify:
    - Restart wazo-ui
    - Reload nginx

- name: Install custom private key for HTTPS
  ansible.builtin.copy:
    src: "{{ engine_api_https_private_key }}"
    dest: /usr/share/wazo-certs/server.key
    owner: root
    group: www-data
    mode: "0640"
  when: engine_api_https_private_key is defined
  notify:
    - Restart wazo-ui
    - Reload nginx

- name: Install wazo-ui
  become: true
  ansible.builtin.apt:
    name: wazo-ui
    state: present
