---
- name: Install xivo-certs
  ansible.builtin.apt:
    name: xivo-certs
    state: present

- name: Install custom certificate for HTTPS
  ansible.builtin.copy:
    src: "{{ engine_api_https_cert }}"
    dest: /usr/share/xivo-certs/server.crt
    owner: root
    group: www-data
    mode: "0640"
  when: engine_api_https_cert is defined
  notify:
    - Reload nginx

- name: Install custom private key for HTTPS
  ansible.builtin.copy:
    src: "{{ engine_api_https_private_key }}"
    dest: /usr/share/xivo-certs/server.key
    owner: root
    group: www-data
    mode: "0640"
  when: engine_api_https_private_key is defined
  notify:
    - Reload nginx
