---
# Used to switch to user rabbitmq
- name: Install sudo
  apt:
    name: sudo
    state: present

- name: Install RabbitMQ
  apt:
    name: rabbitmq-server
    state: present

- name: Enable Consul discovery in RabbitMQ
  command: "sudo -u rabbitmq rabbitmq-plugins --offline enable rabbitmq_peer_discovery_consul"
  when: runtime and wazo_consul_host is defined

- name: Create /etc/rabbitmq/rabbitmq.conf
  template:
    src: templates/rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf
  when: runtime and wazo_consul_host is defined

- name: Ensure RabbitMQ is restarted
  service:
    name: rabbitmq-server
    state: restarted
