---
# Used to switch to user rabbitmq
- name: Install sudo
  apt:
    name: sudo
    state: present

- name: Install RabbitMQ
  apt:
    name: rabbitmq-server
    state: present

# Used by role2docker project
- name: Enable Consul discovery in RabbitMQ
  command: "sudo -u rabbitmq rabbitmq-plugins --offline enable rabbitmq_peer_discovery_consul"
  when: runtime

- name: Ensure RabbitMQ is restarted
  service:
    name: rabbitmq-server
    state: restarted
