---
# Used to switch to user rabbitmq
- name: Install sudo
  ansible.builtin.apt:
    name: sudo
    state: present

- name: Install RabbitMQ
  ansible.builtin.apt:
    name: rabbitmq-server
    state: present

- name: Ensure RabbitMQ is restarted
  ansible.builtin.service:
    name: rabbitmq-server
    state: restarted
