---
# Used to switch to user rabbitmq
- name: Install sudo
  apt:
    name: sudo
    state: present

- name: Install RabbitMQ
  apt:
    name: rabbitmq-server
    state: present

- name: Ensure RabbitMQ is restarted
  service:
    name: rabbitmq-server
    state: restarted
