---
- name: Install wazo-auth
  apt:
    name: wazo-auth
    state: present

- name: Create default wazo-auth database preconfiguration
  tempfile:
    state: file
    prefix: wazo_auth_debconf_file
  register: wazo_auth_debconf_file

- name: Copy wazo-auth database preconfiguration if needed
  template:
    src: templates/wazo-auth.cfg.j2
    dest: "{{ wazo_auth_debconf_file.path }}"
  when:
    - engine_api_db_admin_password is defined
    - engine_api_db_admin_user is defined
    - engine_api_db_auth_name is defined
    - engine_api_db_auth_password is defined
    - engine_api_db_auth_user is defined
    - engine_api_db_confd_name is defined
    - engine_api_db_confd_password is defined
    - engine_api_db_confd_user is defined
    - engine_api_db_host is defined
    - engine_api_db_port is defined

- name: Reset database options for wazo-auth package
  shell: |
    set -o pipefail
    echo PURGE | debconf-communicate wazo-auth
  args:
    executable: /bin/bash

- name: Reconfigure database options for wazo-auth package
  command: debconf-set-selections "{{ wazo_auth_debconf_file.path }}"

- name: Initialize wazo-auth database
  command: dpkg-reconfigure wazo-auth --frontend noninteractive
