---
- name: Install wazo-auth
  ansible.builtin.apt:
    name: wazo-auth
    state: present

- name: Create default wazo-auth database preconfiguration
  ansible.builtin.tempfile:
    state: file
    prefix: wazo_auth_debconf_file
  register: wazo_auth_debconf_file

- name: Copy wazo-auth database preconfiguration if needed
  ansible.builtin.template:
    src: templates/wazo-auth.cfg.j2
    dest: "{{ wazo_auth_debconf_file.path }}"
    mode: "0600"
  when:
    - engine_api_db_admin_password is defined
    - engine_api_db_admin_user is defined
    - engine_api_db_auth_name is defined
    - engine_api_db_auth_password is defined
    - engine_api_db_auth_user is defined
    - engine_api_db_confd_name is defined
    - engine_api_db_confd_password is defined
    - engine_api_db_confd_user is defined
    - engine_api_db_host is defined
    - engine_api_db_port is defined

- name: Reset database options for wazo-auth package
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      echo PURGE | debconf-communicate wazo-auth
  args:
    executable: /bin/bash
  changed_when: true

- name: Reconfigure database options for wazo-auth package
  ansible.builtin.command: debconf-set-selections "{{ wazo_auth_debconf_file.path }}"
  changed_when: true

- name: Initialize wazo-auth database
  ansible.builtin.command: dpkg-reconfigure wazo-auth --frontend noninteractive
  changed_when: true
