- name: Assert Debian Stretch
  assert:
    that: ansible_distribution == 'Debian' and ansible_distribution_major_version == '9'

- name: Copy wazo-auth database preconfiguration
  template:
    src: templates/wazo-auth.cfg.j2
    dest: /tmp/wazo-auth.cfg
- name: Reconfigure database options for wazo-auth package
  command: debconf-set-selections /tmp/wazo-auth.cfg
- name: Initialize wazo-auth database
  command: dpkg-reconfigure wazo-auth --frontend noninteractive

- name: Install wazo-auth-keys
  apt:
    name: wazo-auth-keys
    state: latest
- name: Create service users with wazo-auth-keys
  command: wazo-auth-keys service update

- name: Copy main database preconfiguration
  template:
    src: templates/xivo-manage-db.cfg.j2
    dest: /tmp/xivo-manage-db.cfg
- name: Apply main database preconfiguration
  command: debconf-set-selections /tmp/xivo-manage-db.cfg
- name: Initialize main database
  command: dpkg-reconfigure xivo-manage-db --frontend noninteractive

- name: Fix Twisted dropin.cache
  command: twistd --help-reactors
- name: Start Wazo services
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - xivo-agid
    - xivo-amid
    - wazo-confd
    - xivo-confgend
    - wazo-calld
    - xivo-provd
    - wazo-websocketd

- name: Pass wizard
  wazo_wizard:
    language: "{{ language }}"
    password: "{{ engine_api_root_password }}"
    engine_api_port: "{{ engine_api_port }}"
    verify_certificate: "{{ verify_certificate }}"
  when: engine_api_configure_wizard == "true"
