---
- name: Install Wazo auth
  include_role:
    name: wazo-auth

- name: Create an index.html for the home page
  become: true
  file:
    src: /var/www/html/index.wazo.html
    dest: /var/www/html/index.html
    state: link
  when: groups['uc_ui'] is not defined

- name: Install wazo-auth-keys
  apt:
    name: wazo-auth-keys
    state: present

- name: Create service users with wazo-auth-keys
  command: wazo-auth-keys service update
  when: runtime

- name: Create default main database preconfiguration
  tempfile:
    state: file
    prefix: xivo_managedb_debconf_file
  register: xivo_managedb_debconf_file

- name: Copy main database preconfiguration
  template:
    src: templates/xivo-manage-db.cfg.j2
    dest: "{{ xivo_managedb_debconf_file.path }}"
  when:
    - engine_api_db_admin_password is defined
    - engine_api_db_admin_user is defined
    - engine_api_db_confd_name is defined
    - engine_api_db_confd_password is defined
    - engine_api_db_confd_user is defined
    - engine_api_db_host is defined
    - engine_api_db_port is defined

- name: Copy main database preconfiguration template
  copy:
    src: templates/xivo-manage-db.cfg.j2
    dest: /etc/xivo-manage-db.cfg.j2

- name: Reset main database options for xivo-manage-db package # noqa 301
  shell: |
    set -o pipefail
    echo PURGE | debconf-communicate xivo-manage-db
  args:
    executable: /bin/bash

- name: Reconfigure main database options # noqa 301
  command: debconf-set-selections "{{ xivo_managedb_debconf_file.path }}"

- name: Initialize main database # noqa 301
  command: dpkg-reconfigure xivo-manage-db --frontend noninteractive

- name: Fix Twisted dropin.cache # noqa 301
  command: twistd3 --help-reactors

- name: Start Wazo services
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - wazo-agid
    - wazo-amid
    - wazo-confd
    - wazo-confgend
    - wazo-calld
    - wazo-provd
    - wazo-websocketd
