- name: Get the home page
  ansible.builtin.uri:
    url: "https://localhost/"
    validate_certs: false
  register: home_page

- name: Debug home_page data
  ansible.builtin.debug:
    var: home_page

- name: Verify redirect url
  ansible.builtin.assert:
    that:
      - home_page.url == "https://localhost/login/"
      - home_page.redirected
