debian_upgrade_first: true

wazo_debian_repo: main
wazo_debian_repo_upgrade: main
wazo_distribution: wazo-dev-buster
wazo_distribution_upgrade: wazo-dev-buster

engine_api_host: localhost
engine_api_port: 443
engine_language: en_US

api_client_name: api-client
api_client_password: api-password
engine_api_configure_wizard: false
tenant_name: my-company

engine_auth_path: /api/auth/0.1
engine_confd_path: /api/confd/1.1
engine_setupd_path: /api/setupd/1.0

# router_advertise_address: democ4.wazo.community
# router_advertise_port: 5060
router_api_endpoint_confd: http://localhost:8000
router_api_db_host: localhost
router_api_db_port: 5432
router_api_db_confd_name: wazo_router_confd
router_api_db_confd_user: wazo_router_confd
router_api_db_confd_password: wazo_router_confd

###################################################################################
# The following variables must only be set for a customized value. The default
# value (written in the comment) is handled by Debian packaging and subject to
# change.
###################################################################################

# engine_api_db_host: localhost
# engine_api_db_port: 5432
# engine_api_listen_address: 127.0.0.1

# engine_api_port_confgend: 8669

# engine_api_db_confd_name: asterisk
# engine_api_db_confd_password: proformatique
# engine_api_db_confd_user: asterisk

# engine_api_db_admin_password:
# engine_api_db_admin_user: postgres

# engine_api_db_auth_name: asterisk
# engine_api_db_auth_password: proformatique
# engine_api_db_auth_user: asterisk

# b2bua_ami_permit_client_address: 127.0.0.1
# b2bua_ami_permit_client_mask: 255.255.255.255
# b2bua_host: localhost
# b2bua_listen_address: 127.0.0.1
# b2bua_port_ami: 5038
# b2bua_port_http: 5039
# b2bua_port_https: 5040
# b2bua_port_sysconfd: 8668

# ari_password: Nasheow8Eag
# ari_username: xivo

# ami_password: eeCho8ied3u
# ami_username: wazo_amid

