---
- name: Upload logs
  hosts: all
  tasks:
    - name: Upload logs
      become: true
      ansible.posix.synchronize:
        src: '/var/log'
        dest: '{{ zuul.executor.log_root }}'
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts: []
