---
- hosts: all
  tasks:
    - name: Install list of packages
      become: yes
      apt: name={{item}} state=installed
      with_items:
        - python3-pip

    - name: Install ansible via pip
      become: yes
      pip:
        name: ansible==2.7.9

    - name: Install paramiko via pip
      become: yes
      pip:
        name: paramiko

    - name: Install postgresql ansible module from galaxy
      become: yes
      command: "ansible-galaxy install -r requirements-postgresql.yml"
      args:
        chdir: "{{ zuul.project.src_dir }}"
